# Generated by Django 3.1.3 on 2020-11-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicuserprofile',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
